# Operations on tensors

In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.rand(3, 5)

In [3]:
#slicing, indexing
print(tensor[1])
print(tensor[:, 0])
print(tensor[:, -1])

tensor([0.0407, 0.7239, 0.8953, 0.3730, 0.4491])
tensor([0.1660, 0.0407, 0.7723])
tensor([0.5002, 0.4491, 0.2378])


In [4]:
#concatenation
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.1660, 0.3774, 0.4919, 0.3926, 0.5002, 0.1660, 0.3774, 0.4919, 0.3926,
         0.5002, 0.1660, 0.3774, 0.4919, 0.3926, 0.5002],
        [0.0407, 0.7239, 0.8953, 0.3730, 0.4491, 0.0407, 0.7239, 0.8953, 0.3730,
         0.4491, 0.0407, 0.7239, 0.8953, 0.3730, 0.4491],
        [0.7723, 0.9804, 0.8356, 0.7106, 0.2378, 0.7723, 0.9804, 0.8356, 0.7106,
         0.2378, 0.7723, 0.9804, 0.8356, 0.7106, 0.2378]])


In [5]:
#multiplication of tensors
#y1, y2, y3 have same values 

##matrix multiplication  
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y1)
print(y2)
print(y3)

tensor([[0.8163, 1.0915, 1.3072],
        [1.0915, 1.6680, 1.8610],
        [1.3072, 1.8610, 2.8173]])
tensor([[0.8163, 1.0915, 1.3072],
        [1.0915, 1.6680, 1.8610],
        [1.3072, 1.8610, 2.8173]])
tensor([[0.8163, 1.0915, 1.3072],
        [1.0915, 1.6680, 1.8610],
        [1.3072, 1.8610, 2.8173]])


In [6]:
##element wise multiplication
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(z1)
torch.mul(tensor, tensor, out=z3)
print(z1)
print(z2)
print(z3)

tensor([[0.0276, 0.1425, 0.2420, 0.1541, 0.2502],
        [0.0017, 0.5240, 0.8016, 0.1391, 0.2017],
        [0.5965, 0.9611, 0.6982, 0.5050, 0.0565]])
tensor([[0.0276, 0.1425, 0.2420, 0.1541, 0.2502],
        [0.0017, 0.5240, 0.8016, 0.1391, 0.2017],
        [0.5965, 0.9611, 0.6982, 0.5050, 0.0565]])
tensor([[0.0276, 0.1425, 0.2420, 0.1541, 0.2502],
        [0.0017, 0.5240, 0.8016, 0.1391, 0.2017],
        [0.5965, 0.9611, 0.6982, 0.5050, 0.0565]])


In [7]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

7.946783542633057 <class 'float'>


In [8]:
tensor1 = torch.zeros(5, 5)
tensor1.add_(5)
print(tensor1)

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])


In [14]:
##tensors on CPU and NumPy arrays can share the same memory space
##changing one will change the other
t = torch.rand(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([0.1435, 0.6369, 0.3346, 0.0501, 0.0251])
n: [0.14351594 0.63686794 0.33460778 0.05007493 0.02514005]


In [13]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2.8878, 2.4513, 2.5560, 2.5360, 2.1442])
n: [2.8878129 2.451312  2.5559804 2.5360034 2.1442142]


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
